# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/UI/Componentes/FiltroRemanufatura.ui',
# licensing of 'Resources/UI/Componentes/FiltroRemanufatura.ui' applies.
#
# Created: Sun Nov 10 17:47:18 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FiltroRemanufatura(object):
    def setupUi(self, FiltroRemanufatura):
        FiltroRemanufatura.setObjectName("FiltroRemanufatura")
        FiltroRemanufatura.resize(645, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FiltroRemanufatura.sizePolicy().hasHeightForWidth())
        FiltroRemanufatura.setSizePolicy(sizePolicy)
        FiltroRemanufatura.setMinimumSize(QtCore.QSize(600, 250))
        FiltroRemanufatura.setMaximumSize(QtCore.QSize(645, 280))
        FiltroRemanufatura.setSizeIncrement(QtCore.QSize(100, 50))
        FiltroRemanufatura.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        FiltroRemanufatura.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(FiltroRemanufatura)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(FiltroRemanufatura)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.frame.setFont(font)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formFrame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formFrame.sizePolicy().hasHeightForWidth())
        self.formFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.formFrame.setFont(font)
        self.formFrame.setObjectName("formFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.formFrame)
        self.gridLayout_3.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_situacao = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_situacao.sizePolicy().hasHeightForWidth())
        self.groupBox_situacao.setSizePolicy(sizePolicy)
        self.groupBox_situacao.setObjectName("groupBox_situacao")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_situacao)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_cadastrada = QtWidgets.QCheckBox(self.groupBox_situacao)
        self.checkBox_cadastrada.setObjectName("checkBox_cadastrada")
        self.verticalLayout_2.addWidget(self.checkBox_cadastrada)
        self.checkBox_realizada = QtWidgets.QCheckBox(self.groupBox_situacao)
        self.checkBox_realizada.setObjectName("checkBox_realizada")
        self.verticalLayout_2.addWidget(self.checkBox_realizada)
        self.checkBox_encerrada = QtWidgets.QCheckBox(self.groupBox_situacao)
        self.checkBox_encerrada.setEnabled(True)
        self.checkBox_encerrada.setObjectName("checkBox_encerrada")
        self.verticalLayout_2.addWidget(self.checkBox_encerrada)
        self.verticalLayout_4.addWidget(self.groupBox_situacao)
        self.groupBox_classificacao = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_classificacao.sizePolicy().hasHeightForWidth())
        self.groupBox_classificacao.setSizePolicy(sizePolicy)
        self.groupBox_classificacao.setObjectName("groupBox_classificacao")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_classificacao)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_colorido = QtWidgets.QCheckBox(self.groupBox_classificacao)
        self.checkBox_colorido.setObjectName("checkBox_colorido")
        self.verticalLayout.addWidget(self.checkBox_colorido)
        self.checkBox_PB = QtWidgets.QCheckBox(self.groupBox_classificacao)
        self.checkBox_PB.setObjectName("checkBox_PB")
        self.verticalLayout.addWidget(self.checkBox_PB)
        self.verticalLayout_4.addWidget(self.groupBox_classificacao)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox_2.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox_2.setSizePolicy(sizePolicy)
        self.horizontalGroupBox_2.setCheckable(False)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_cliente_documento = QtWidgets.QLineEdit(self.horizontalGroupBox_2)
        self.lineEdit_cliente_documento.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_cliente_documento.setObjectName("lineEdit_cliente_documento")
        self.horizontalLayout_2.addWidget(self.lineEdit_cliente_documento)
        self.toolButton_cliente = QtWidgets.QToolButton(self.horizontalGroupBox_2)
        self.toolButton_cliente.setText("")
        self.toolButton_cliente.setObjectName("toolButton_cliente")
        self.horizontalLayout_2.addWidget(self.toolButton_cliente)
        self.lineEdit_cliente = QtWidgets.QLineEdit(self.horizontalGroupBox_2)
        self.lineEdit_cliente.setEnabled(False)
        self.lineEdit_cliente.setObjectName("lineEdit_cliente")
        self.horizontalLayout_2.addWidget(self.lineEdit_cliente)
        self.verticalLayout_5.addWidget(self.horizontalGroupBox_2)
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox_3.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox_3.setSizePolicy(sizePolicy)
        self.horizontalGroupBox_3.setCheckable(False)
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_mercadoria_id = QtWidgets.QLineEdit(self.horizontalGroupBox_3)
        self.lineEdit_mercadoria_id.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_mercadoria_id.setObjectName("lineEdit_mercadoria_id")
        self.horizontalLayout_3.addWidget(self.lineEdit_mercadoria_id)
        self.toolButton_mercadoria = QtWidgets.QToolButton(self.horizontalGroupBox_3)
        self.toolButton_mercadoria.setText("")
        self.toolButton_mercadoria.setObjectName("toolButton_mercadoria")
        self.horizontalLayout_3.addWidget(self.toolButton_mercadoria)
        self.lineEdit_mercadoria = QtWidgets.QLineEdit(self.horizontalGroupBox_3)
        self.lineEdit_mercadoria.setEnabled(False)
        self.lineEdit_mercadoria.setObjectName("lineEdit_mercadoria")
        self.horizontalLayout_3.addWidget(self.lineEdit_mercadoria)
        self.verticalLayout_5.addWidget(self.horizontalGroupBox_3)
        self.widget_4 = QtWidgets.QWidget(self.frame_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_cadastro = QtWidgets.QGroupBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_cadastro.sizePolicy().hasHeightForWidth())
        self.groupBox_cadastro.setSizePolicy(sizePolicy)
        self.groupBox_cadastro.setCheckable(True)
        self.groupBox_cadastro.setChecked(False)
        self.groupBox_cadastro.setObjectName("groupBox_cadastro")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_cadastro)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateEdit_data_entrada1 = QtWidgets.QDateEdit(self.groupBox_cadastro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_data_entrada1.sizePolicy().hasHeightForWidth())
        self.dateEdit_data_entrada1.setSizePolicy(sizePolicy)
        self.dateEdit_data_entrada1.setWrapping(False)
        self.dateEdit_data_entrada1.setFrame(False)
        self.dateEdit_data_entrada1.setReadOnly(False)
        self.dateEdit_data_entrada1.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_data_entrada1.setCalendarPopup(True)
        self.dateEdit_data_entrada1.setDate(QtCore.QDate(2019, 1, 1))
        self.dateEdit_data_entrada1.setObjectName("dateEdit_data_entrada1")
        self.horizontalLayout.addWidget(self.dateEdit_data_entrada1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_cadastro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dateEdit_data_entrada2 = QtWidgets.QDateEdit(self.groupBox_cadastro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_data_entrada2.sizePolicy().hasHeightForWidth())
        self.dateEdit_data_entrada2.setSizePolicy(sizePolicy)
        self.dateEdit_data_entrada2.setWrapping(False)
        self.dateEdit_data_entrada2.setFrame(False)
        self.dateEdit_data_entrada2.setReadOnly(False)
        self.dateEdit_data_entrada2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_data_entrada2.setCalendarPopup(True)
        self.dateEdit_data_entrada2.setDate(QtCore.QDate(2019, 12, 31))
        self.dateEdit_data_entrada2.setObjectName("dateEdit_data_entrada2")
        self.horizontalLayout.addWidget(self.dateEdit_data_entrada2)
        self.horizontalLayout_6.addWidget(self.groupBox_cadastro)
        self.groupBox_realizada = QtWidgets.QGroupBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_realizada.sizePolicy().hasHeightForWidth())
        self.groupBox_realizada.setSizePolicy(sizePolicy)
        self.groupBox_realizada.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_realizada.setCheckable(True)
        self.groupBox_realizada.setChecked(False)
        self.groupBox_realizada.setObjectName("groupBox_realizada")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_realizada)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dateEdit_data_saida1 = QtWidgets.QDateEdit(self.groupBox_realizada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_data_saida1.sizePolicy().hasHeightForWidth())
        self.dateEdit_data_saida1.setSizePolicy(sizePolicy)
        self.dateEdit_data_saida1.setWrapping(False)
        self.dateEdit_data_saida1.setFrame(False)
        self.dateEdit_data_saida1.setReadOnly(False)
        self.dateEdit_data_saida1.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_data_saida1.setCalendarPopup(True)
        self.dateEdit_data_saida1.setDate(QtCore.QDate(2019, 1, 1))
        self.dateEdit_data_saida1.setObjectName("dateEdit_data_saida1")
        self.horizontalLayout_4.addWidget(self.dateEdit_data_saida1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_realizada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.dateEdit_data_saida2 = QtWidgets.QDateEdit(self.groupBox_realizada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_data_saida2.sizePolicy().hasHeightForWidth())
        self.dateEdit_data_saida2.setSizePolicy(sizePolicy)
        self.dateEdit_data_saida2.setWrapping(False)
        self.dateEdit_data_saida2.setFrame(False)
        self.dateEdit_data_saida2.setReadOnly(False)
        self.dateEdit_data_saida2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_data_saida2.setCalendarPopup(True)
        self.dateEdit_data_saida2.setDate(QtCore.QDate(2019, 12, 31))
        self.dateEdit_data_saida2.setObjectName("dateEdit_data_saida2")
        self.horizontalLayout_4.addWidget(self.dateEdit_data_saida2)
        self.horizontalLayout_6.addWidget(self.groupBox_realizada)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.formFrame, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(FiltroRemanufatura)
        QtCore.QMetaObject.connectSlotsByName(FiltroRemanufatura)

    def retranslateUi(self, FiltroRemanufatura):
        FiltroRemanufatura.setWindowTitle(QtWidgets.QApplication.translate("FiltroRemanufatura", "Filtro Remanufatura", None, -1))
        self.groupBox_situacao.setTitle(QtWidgets.QApplication.translate("FiltroRemanufatura", "Situação", None, -1))
        self.checkBox_cadastrada.setText(QtWidgets.QApplication.translate("FiltroRemanufatura", "Cadastrada", None, -1))
        self.checkBox_realizada.setText(QtWidgets.QApplication.translate("FiltroRemanufatura", "Realizada", None, -1))
        self.checkBox_encerrada.setText(QtWidgets.QApplication.translate("FiltroRemanufatura", "Encerrada", None, -1))
        self.groupBox_classificacao.setTitle(QtWidgets.QApplication.translate("FiltroRemanufatura", "Cor", None, -1))
        self.checkBox_colorido.setText(QtWidgets.QApplication.translate("FiltroRemanufatura", "Colorida", None, -1))
        self.checkBox_PB.setText(QtWidgets.QApplication.translate("FiltroRemanufatura", "P&&&B", None, -1))
        self.horizontalGroupBox_2.setTitle(QtWidgets.QApplication.translate("FiltroRemanufatura", "Cliente", None, -1))
        self.horizontalGroupBox_3.setTitle(QtWidgets.QApplication.translate("FiltroRemanufatura", "Casco", None, -1))
        self.groupBox_cadastro.setTitle(QtWidgets.QApplication.translate("FiltroRemanufatura", "Data de cadastro", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("FiltroRemanufatura", "até", None, -1))
        self.groupBox_realizada.setTitle(QtWidgets.QApplication.translate("FiltroRemanufatura", "Data realização", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("FiltroRemanufatura", "até", None, -1))

