# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/UI/Componentes/FiltroEstoqueConsolidado.ui',
# licensing of 'Resources/UI/Componentes/FiltroEstoqueConsolidado.ui' applies.
#
# Created: Sun Nov  3 01:20:55 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FiltroEstoqueConsolidado(object):
    def setupUi(self, FiltroEstoqueConsolidado):
        FiltroEstoqueConsolidado.setObjectName("FiltroEstoqueConsolidado")
        FiltroEstoqueConsolidado.resize(695, 260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FiltroEstoqueConsolidado.sizePolicy().hasHeightForWidth())
        FiltroEstoqueConsolidado.setSizePolicy(sizePolicy)
        FiltroEstoqueConsolidado.setMinimumSize(QtCore.QSize(600, 250))
        FiltroEstoqueConsolidado.setMaximumSize(QtCore.QSize(695, 260))
        FiltroEstoqueConsolidado.setSizeIncrement(QtCore.QSize(100, 50))
        FiltroEstoqueConsolidado.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        FiltroEstoqueConsolidado.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(FiltroEstoqueConsolidado)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(FiltroEstoqueConsolidado)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.frame.setFont(font)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formFrame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formFrame.sizePolicy().hasHeightForWidth())
        self.formFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.formFrame.setFont(font)
        self.formFrame.setObjectName("formFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.formFrame)
        self.gridLayout_3.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_data_base = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_data_base.setCheckable(True)
        self.groupBox_data_base.setObjectName("groupBox_data_base")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_data_base)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dateEdit_data_base = QtWidgets.QDateEdit(self.groupBox_data_base)
        self.dateEdit_data_base.setCalendarPopup(True)
        self.dateEdit_data_base.setDate(QtCore.QDate(2019, 1, 1))
        self.dateEdit_data_base.setObjectName("dateEdit_data_base")
        self.horizontalLayout_5.addWidget(self.dateEdit_data_base)
        self.verticalLayout_4.addWidget(self.groupBox_data_base)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_inativos = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_inativos.setEnabled(True)
        self.checkBox_inativos.setObjectName("checkBox_inativos")
        self.verticalLayout_2.addWidget(self.checkBox_inativos)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox_2.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox_2.setSizePolicy(sizePolicy)
        self.horizontalGroupBox_2.setCheckable(False)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_fornecedor_documento = QtWidgets.QLineEdit(self.horizontalGroupBox_2)
        self.lineEdit_fornecedor_documento.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_fornecedor_documento.setObjectName("lineEdit_fornecedor_documento")
        self.horizontalLayout_2.addWidget(self.lineEdit_fornecedor_documento)
        self.lineEdit_fornecedor = QtWidgets.QLineEdit(self.horizontalGroupBox_2)
        self.lineEdit_fornecedor.setEnabled(False)
        self.lineEdit_fornecedor.setObjectName("lineEdit_fornecedor")
        self.horizontalLayout_2.addWidget(self.lineEdit_fornecedor)
        self.verticalLayout_5.addWidget(self.horizontalGroupBox_2)
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox_3.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox_3.setSizePolicy(sizePolicy)
        self.horizontalGroupBox_3.setCheckable(False)
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_mercadoria_id = QtWidgets.QLineEdit(self.horizontalGroupBox_3)
        self.lineEdit_mercadoria_id.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_mercadoria_id.setObjectName("lineEdit_mercadoria_id")
        self.horizontalLayout_3.addWidget(self.lineEdit_mercadoria_id)
        self.lineEdit_mercadoria = QtWidgets.QLineEdit(self.horizontalGroupBox_3)
        self.lineEdit_mercadoria.setEnabled(False)
        self.lineEdit_mercadoria.setObjectName("lineEdit_mercadoria")
        self.horizontalLayout_3.addWidget(self.lineEdit_mercadoria)
        self.verticalLayout_5.addWidget(self.horizontalGroupBox_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_casco = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_casco.setObjectName("checkBox_casco")
        self.horizontalLayout.addWidget(self.checkBox_casco)
        self.checkBox_insumo = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_insumo.setObjectName("checkBox_insumo")
        self.horizontalLayout.addWidget(self.checkBox_insumo)
        self.checkBox_mercadoria = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_mercadoria.setObjectName("checkBox_mercadoria")
        self.horizontalLayout.addWidget(self.checkBox_mercadoria)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.widget_4 = QtWidgets.QWidget(self.frame_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5.addWidget(self.widget_4)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.formFrame, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(FiltroEstoqueConsolidado)
        QtCore.QMetaObject.connectSlotsByName(FiltroEstoqueConsolidado)

    def retranslateUi(self, FiltroEstoqueConsolidado):
        FiltroEstoqueConsolidado.setWindowTitle(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Filtro Estoque Consolidado", None, -1))
        self.groupBox_data_base.setTitle(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Data base", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Estoque", None, -1))
        self.checkBox_inativos.setText(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Exibir inativos", None, -1))
        self.horizontalGroupBox_2.setTitle(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Fornecedor", None, -1))
        self.horizontalGroupBox_3.setTitle(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Mercadoria", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Classificação", None, -1))
        self.checkBox_casco.setText(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Casco", None, -1))
        self.checkBox_insumo.setText(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Insumo", None, -1))
        self.checkBox_mercadoria.setText(QtWidgets.QApplication.translate("FiltroEstoqueConsolidado", "Mercadoria", None, -1))

