# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources\UI\Componentes\relatoriopadrao.ui',
# licensing of 'Resources\UI\Componentes\relatoriopadrao.ui' applies.
#
# Created: Sun Sep 15 22:19:14 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RelatorioPadrao(object):
    def setupUi(self, RelatorioPadrao):
        RelatorioPadrao.setObjectName("RelatorioPadrao")
        RelatorioPadrao.resize(1064, 659)
        self.gridLayout = QtWidgets.QGridLayout(RelatorioPadrao)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_menu = QtWidgets.QWidget(RelatorioPadrao)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu.sizePolicy().hasHeightForWidth())
        self.frame_menu.setSizePolicy(sizePolicy)
        self.frame_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.frame.setFont(font)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_atualizar = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_atualizar.setFont(font)
        self.pushButton_atualizar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_atualizar.setCheckable(False)
        self.pushButton_atualizar.setDefault(False)
        self.pushButton_atualizar.setFlat(True)
        self.pushButton_atualizar.setObjectName("pushButton_atualizar")
        self.horizontalLayout_3.addWidget(self.pushButton_atualizar)
        self.pushButton_filtro = QtWidgets.QPushButton(self.frame)
        self.pushButton_filtro.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_filtro.sizePolicy().hasHeightForWidth())
        self.pushButton_filtro.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_filtro.setFont(font)
        self.pushButton_filtro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_filtro.setCheckable(False)
        self.pushButton_filtro.setDefault(False)
        self.pushButton_filtro.setFlat(True)
        self.pushButton_filtro.setObjectName("pushButton_filtro")
        self.horizontalLayout_3.addWidget(self.pushButton_filtro)
        self.horizontalLayout_4.addWidget(self.frame)
        self.stackedWidget_filtros = QtWidgets.QStackedWidget(self.frame_menu)
        self.stackedWidget_filtros.setObjectName("stackedWidget_filtros")
        self.stackedWidget_filtrosPage1 = QtWidgets.QWidget()
        self.stackedWidget_filtrosPage1.setObjectName("stackedWidget_filtrosPage1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.stackedWidget_filtrosPage1)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.stackedWidget_filtrosPage1)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_5.addWidget(self.checkBox_2)
        self.horizontalWidget = QtWidgets.QWidget(self.stackedWidget_filtrosPage1)
        self.horizontalWidget.setEnabled(False)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_data = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_data.setSpacing(5)
        self.horizontalLayout_data.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_data.setObjectName("horizontalLayout_data")
        self.label = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_data.addWidget(self.label)
        self.dateEdit = QtWidgets.QDateEdit(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_data.addWidget(self.dateEdit)
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_data.addWidget(self.label_2)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_2.sizePolicy().hasHeightForWidth())
        self.dateEdit_2.setSizePolicy(sizePolicy)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_data.addWidget(self.dateEdit_2)
        self.horizontalLayout_5.addWidget(self.horizontalWidget)
        self.checkBox = QtWidgets.QCheckBox(self.stackedWidget_filtrosPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.stackedWidget_filtros.addWidget(self.stackedWidget_filtrosPage1)
        self.horizontalLayout_4.addWidget(self.stackedWidget_filtros)
        self.verticalLayout.addWidget(self.frame_menu)
        self.frame_contents = QtWidgets.QFrame(RelatorioPadrao)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_contents.sizePolicy().hasHeightForWidth())
        self.frame_contents.setSizePolicy(sizePolicy)
        self.frame_contents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contents.setObjectName("frame_contents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_contents)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame_contents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_tabela = QtWidgets.QTableWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.tableWidget_tabela.setFont(font)
        self.tableWidget_tabela.setAlternatingRowColors(True)
        self.tableWidget_tabela.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_tabela.setObjectName("tableWidget_tabela")
        self.tableWidget_tabela.setColumnCount(0)
        self.tableWidget_tabela.setRowCount(0)
        self.tableWidget_tabela.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget_tabela.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_tabela.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_tabela.verticalHeader().setVisible(False)
        self.tableWidget_tabela.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_2.addWidget(self.tableWidget_tabela)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.frame_contents)
        self.frame_buttons = QtWidgets.QFrame(RelatorioPadrao)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons.sizePolicy().hasHeightForWidth())
        self.frame_buttons.setSizePolicy(sizePolicy)
        self.frame_buttons.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_buttons.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_buttons)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout.addWidget(self.frame_buttons)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(RelatorioPadrao)
        QtCore.QMetaObject.connectSlotsByName(RelatorioPadrao)

    def retranslateUi(self, RelatorioPadrao):
        RelatorioPadrao.setWindowTitle(QtWidgets.QApplication.translate("RelatorioPadrao", "Form", None, -1))
        self.pushButton_atualizar.setText(QtWidgets.QApplication.translate("RelatorioPadrao", "Atualizar", None, -1))
        self.pushButton_filtro.setText(QtWidgets.QApplication.translate("RelatorioPadrao", "Filtro", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("RelatorioPadrao", "Data", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("RelatorioPadrao", "até", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("RelatorioPadrao", "Apenas X", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("RelatorioPadrao", "Relatório", None, -1))
        self.tableWidget_tabela.setSortingEnabled(True)

