# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources\UI\Componentes\relatoriopadrao.ui',
# licensing of 'Resources\UI\Componentes\relatoriopadrao.ui' applies.
#
# Created: Sun Sep 15 19:04:17 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RelatorioPadrao(object):
    def setupUi(self, RelatorioPadrao):
        RelatorioPadrao.setObjectName("RelatorioPadrao")
        RelatorioPadrao.resize(1064, 659)
        self.gridLayout = QtWidgets.QGridLayout(RelatorioPadrao)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_menu = QtWidgets.QWidget(RelatorioPadrao)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu.sizePolicy().hasHeightForWidth())
        self.frame_menu.setSizePolicy(sizePolicy)
        self.frame_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_menu)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.frame.setFont(font)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_atualizar = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_atualizar.setFont(font)
        self.pushButton_atualizar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_atualizar.setCheckable(False)
        self.pushButton_atualizar.setDefault(False)
        self.pushButton_atualizar.setFlat(True)
        self.pushButton_atualizar.setObjectName("pushButton_atualizar")
        self.horizontalLayout_3.addWidget(self.pushButton_atualizar)
        self.pushButton_filtro = QtWidgets.QPushButton(self.frame)
        self.pushButton_filtro.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_filtro.setFont(font)
        self.pushButton_filtro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_filtro.setCheckable(False)
        self.pushButton_filtro.setDefault(False)
        self.pushButton_filtro.setFlat(True)
        self.pushButton_filtro.setObjectName("pushButton_filtro")
        self.horizontalLayout_3.addWidget(self.pushButton_filtro)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_menu)
        self.frame_contents = QtWidgets.QFrame(RelatorioPadrao)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_contents.sizePolicy().hasHeightForWidth())
        self.frame_contents.setSizePolicy(sizePolicy)
        self.frame_contents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contents.setObjectName("frame_contents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_contents)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame_contents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_tabela = QtWidgets.QTableWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.tableWidget_tabela.setFont(font)
        self.tableWidget_tabela.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_tabela.setObjectName("tableWidget_tabela")
        self.tableWidget_tabela.setColumnCount(0)
        self.tableWidget_tabela.setRowCount(0)
        self.tableWidget_tabela.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_tabela.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tableWidget_tabela)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.frame_contents)
        self.frame_buttons = QtWidgets.QFrame(RelatorioPadrao)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons.sizePolicy().hasHeightForWidth())
        self.frame_buttons.setSizePolicy(sizePolicy)
        self.frame_buttons.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_buttons.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_buttons)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout.addWidget(self.frame_buttons)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(RelatorioPadrao)
        QtCore.QMetaObject.connectSlotsByName(RelatorioPadrao)

    def retranslateUi(self, RelatorioPadrao):
        RelatorioPadrao.setWindowTitle(QtWidgets.QApplication.translate("RelatorioPadrao", "Form", None, -1))
        self.pushButton_atualizar.setText(QtWidgets.QApplication.translate("RelatorioPadrao", "Atualizar", None, -1))
        self.pushButton_filtro.setText(QtWidgets.QApplication.translate("RelatorioPadrao", "Filtro", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("RelatorioPadrao", "Relatório", None, -1))
        self.tableWidget_tabela.setSortingEnabled(True)

