# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Lucas\PycharmProjects\Projeto-SOAD\Resources\UI\LoginDialog.ui'
#
# Created: Sun Jul 28 16:11:44 2019
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(440, 290)
        LoginDialog.setMinimumSize(QtCore.QSize(440, 290))
        LoginDialog.setMaximumSize(QtCore.QSize(440, 290))
        self.scrollArea = QtWidgets.QScrollArea(LoginDialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 421, 271))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 269))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(419, 269))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(419, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget_servidor = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalWidget_servidor.setObjectName("verticalWidget_servidor")
        self.verticalLayout_servidor = QtWidgets.QVBoxLayout(self.verticalWidget_servidor)
        self.verticalLayout_servidor.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_servidor.setObjectName("verticalLayout_servidor")
        self.label_servidor = QtWidgets.QLabel(self.verticalWidget_servidor)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_servidor.setFont(font)
        self.label_servidor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servidor.setObjectName("label_servidor")
        self.verticalLayout_servidor.addWidget(self.label_servidor)
        self.comboBox_servidor = QtWidgets.QComboBox(self.verticalWidget_servidor)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_servidor.setFont(font)
        self.comboBox_servidor.setObjectName("comboBox_servidor")
        self.verticalLayout_servidor.addWidget(self.comboBox_servidor)
        self.verticalLayout_2.addWidget(self.verticalWidget_servidor)
        self.verticalWidget_login = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalWidget_login.setObjectName("verticalWidget_login")
        self.verticalLayout_login = QtWidgets.QVBoxLayout(self.verticalWidget_login)
        self.verticalLayout_login.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_login.setObjectName("verticalLayout_login")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_login.addItem(spacerItem)
        self.label_usuario = QtWidgets.QLabel(self.verticalWidget_login)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_usuario.setFont(font)
        self.label_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.label_usuario.setObjectName("label_usuario")
        self.verticalLayout_login.addWidget(self.label_usuario)
        self.lineEdit_usuario = QtWidgets.QLineEdit(self.verticalWidget_login)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_usuario.setFont(font)
        self.lineEdit_usuario.setObjectName("lineEdit_usuario")
        self.verticalLayout_login.addWidget(self.lineEdit_usuario)
        self.label_senha = QtWidgets.QLabel(self.verticalWidget_login)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_senha.setFont(font)
        self.label_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.label_senha.setObjectName("label_senha")
        self.verticalLayout_login.addWidget(self.label_senha)
        self.lineEdit_senha = QtWidgets.QLineEdit(self.verticalWidget_login)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_senha.setFont(font)
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.verticalLayout_login.addWidget(self.lineEdit_senha)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_login.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalWidget_login)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_login.addWidget(self.buttonBox)
        self.verticalLayout_2.addWidget(self.verticalWidget_login)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        LoginDialog.setWindowTitle(QtWidgets.QApplication.translate("LoginDialog", "SOAD - Login", None, -1))
        self.label_servidor.setText(QtWidgets.QApplication.translate("LoginDialog", "Servidor", None, -1))
        self.label_usuario.setText(QtWidgets.QApplication.translate("LoginDialog", "Usuário", None, -1))
        self.label_senha.setText(QtWidgets.QApplication.translate("LoginDialog", "Senha", None, -1))

