# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/UI/RegistroRemanufatura.ui',
# licensing of 'Resources/UI/RegistroRemanufatura.ui' applies.
#
# Created: Sun Nov 10 17:47:14 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RegistroRemanufatura(object):
    def setupUi(self, RegistroRemanufatura):
        RegistroRemanufatura.setObjectName("RegistroRemanufatura")
        RegistroRemanufatura.resize(940, 610)
        RegistroRemanufatura.setMinimumSize(QtCore.QSize(900, 600))
        self.gridLayout = QtWidgets.QGridLayout(RegistroRemanufatura)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(RegistroRemanufatura)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_identificacao = QtWidgets.QGroupBox(self.frame)
        self.groupBox_identificacao.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_identificacao.setFont(font)
        self.groupBox_identificacao.setFlat(False)
        self.groupBox_identificacao.setObjectName("groupBox_identificacao")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_identificacao)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setContentsMargins(9, 9, 9, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameFormLayout_remanufatura = QtWidgets.QFrame(self.groupBox_identificacao)
        self.frameFormLayout_remanufatura.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.frameFormLayout_remanufatura.setFont(font)
        self.frameFormLayout_remanufatura.setObjectName("frameFormLayout_remanufatura")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frameFormLayout_remanufatura)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setHorizontalSpacing(9)
        self.formLayout_5.setVerticalSpacing(10)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_codigo = QtWidgets.QLabel(self.frameFormLayout_remanufatura)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_codigo.setFont(font)
        self.label_codigo.setObjectName("label_codigo")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_codigo)
        self.horizontalFrame_4 = QtWidgets.QFrame(self.frameFormLayout_remanufatura)
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_codigo = QtWidgets.QLineEdit(self.horizontalFrame_4)
        self.lineEdit_codigo.setEnabled(False)
        self.lineEdit_codigo.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_codigo.setToolTipDuration(10000)
        self.lineEdit_codigo.setMaxLength(15)
        self.lineEdit_codigo.setObjectName("lineEdit_codigo")
        self.horizontalLayout_2.addWidget(self.lineEdit_codigo)
        self.spinBox_quantidade = QtWidgets.QSpinBox(self.horizontalFrame_4)
        self.spinBox_quantidade.setMinimumSize(QtCore.QSize(0, 27))
        self.spinBox_quantidade.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_quantidade.setWrapping(False)
        self.spinBox_quantidade.setFrame(True)
        self.spinBox_quantidade.setReadOnly(False)
        self.spinBox_quantidade.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_quantidade.setSpecialValueText("")
        self.spinBox_quantidade.setProperty("showGroupSeparator", False)
        self.spinBox_quantidade.setMinimum(1)
        self.spinBox_quantidade.setObjectName("spinBox_quantidade")
        self.horizontalLayout_2.addWidget(self.spinBox_quantidade)
        self.label_pedido_id = QtWidgets.QLabel(self.horizontalFrame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_pedido_id.setFont(font)
        self.label_pedido_id.setText("")
        self.label_pedido_id.setObjectName("label_pedido_id")
        self.horizontalLayout_2.addWidget(self.label_pedido_id)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.horizontalFrame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_medida = QtWidgets.QLabel(self.horizontalFrame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_medida.setFont(font)
        self.label_medida.setObjectName("label_medida")
        self.horizontalLayout_2.addWidget(self.label_medida)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalFrame_4)
        self.label_casco = QtWidgets.QLabel(self.frameFormLayout_remanufatura)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_casco.setFont(font)
        self.label_casco.setObjectName("label_casco")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_casco)
        self.horizontalLayout_casco = QtWidgets.QHBoxLayout()
        self.horizontalLayout_casco.setSpacing(10)
        self.horizontalLayout_casco.setObjectName("horizontalLayout_casco")
        self.lineEdit_casco_id = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_casco_id.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_casco_id.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_casco_id.setInputMask("")
        self.lineEdit_casco_id.setObjectName("lineEdit_casco_id")
        self.horizontalLayout_casco.addWidget(self.lineEdit_casco_id)
        self.toolButton_casco = QtWidgets.QToolButton(self.frameFormLayout_remanufatura)
        self.toolButton_casco.setText("")
        self.toolButton_casco.setObjectName("toolButton_casco")
        self.horizontalLayout_casco.addWidget(self.toolButton_casco)
        self.lineEdit_casco = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_casco.setEnabled(False)
        self.lineEdit_casco.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_casco.setObjectName("lineEdit_casco")
        self.horizontalLayout_casco.addWidget(self.lineEdit_casco)
        self.lineEdit_marca_casco = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_marca_casco.setEnabled(False)
        self.lineEdit_marca_casco.setObjectName("lineEdit_marca_casco")
        self.horizontalLayout_casco.addWidget(self.lineEdit_marca_casco)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_casco)
        self.label_insumo = QtWidgets.QLabel(self.frameFormLayout_remanufatura)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_insumo.setFont(font)
        self.label_insumo.setObjectName("label_insumo")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_insumo)
        self.horizontalLayout_insumo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_insumo.setSpacing(10)
        self.horizontalLayout_insumo.setObjectName("horizontalLayout_insumo")
        self.lineEdit_insumo_id = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_insumo_id.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_insumo_id.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_insumo_id.setInputMask("")
        self.lineEdit_insumo_id.setObjectName("lineEdit_insumo_id")
        self.horizontalLayout_insumo.addWidget(self.lineEdit_insumo_id)
        self.toolButton_insumo = QtWidgets.QToolButton(self.frameFormLayout_remanufatura)
        self.toolButton_insumo.setText("")
        self.toolButton_insumo.setObjectName("toolButton_insumo")
        self.horizontalLayout_insumo.addWidget(self.toolButton_insumo)
        self.lineEdit_insumo = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_insumo.setEnabled(False)
        self.lineEdit_insumo.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_insumo.setObjectName("lineEdit_insumo")
        self.horizontalLayout_insumo.addWidget(self.lineEdit_insumo)
        self.lineEdit_marca_insumo = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_marca_insumo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_marca_insumo.sizePolicy().hasHeightForWidth())
        self.lineEdit_marca_insumo.setSizePolicy(sizePolicy)
        self.lineEdit_marca_insumo.setObjectName("lineEdit_marca_insumo")
        self.horizontalLayout_insumo.addWidget(self.lineEdit_marca_insumo)
        self.formLayout_5.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_insumo)
        self.horizontalLayout.addWidget(self.frameFormLayout_remanufatura)
        self.buttonBox_remanufatura = QtWidgets.QDialogButtonBox(self.groupBox_identificacao)
        self.buttonBox_remanufatura.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.buttonBox_remanufatura.setFont(font)
        self.buttonBox_remanufatura.setMouseTracking(False)
        self.buttonBox_remanufatura.setAutoFillBackground(False)
        self.buttonBox_remanufatura.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox_remanufatura.setStandardButtons(QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox_remanufatura.setCenterButtons(True)
        self.buttonBox_remanufatura.setObjectName("buttonBox_remanufatura")
        self.horizontalLayout.addWidget(self.buttonBox_remanufatura)
        self.label_tinta = QtWidgets.QLabel(self.groupBox_identificacao)
        self.label_tinta.setMinimumSize(QtCore.QSize(190, 0))
        self.label_tinta.setSizeIncrement(QtCore.QSize(256, 0))
        self.label_tinta.setBaseSize(QtCore.QSize(0, 0))
        self.label_tinta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tinta.setObjectName("label_tinta")
        self.horizontalLayout.addWidget(self.label_tinta)
        self.gridLayout_2.addWidget(self.groupBox_identificacao, 0, 0, 1, 1)
        self.frame_botoes = QtWidgets.QFrame(self.frame)
        self.frame_botoes.setObjectName("frame_botoes")
        self.frame_buttonsLayout = QtWidgets.QHBoxLayout(self.frame_botoes)
        self.frame_buttonsLayout.setSpacing(10)
        self.frame_buttonsLayout.setContentsMargins(9, 9, 9, 9)
        self.frame_buttonsLayout.setObjectName("frame_buttonsLayout")
        self.label_situacao = QtWidgets.QLabel(self.frame_botoes)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_situacao.setFont(font)
        self.label_situacao.setToolTipDuration(10000)
        self.label_situacao.setObjectName("label_situacao")
        self.frame_buttonsLayout.addWidget(self.label_situacao)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.frame_buttonsLayout.addItem(spacerItem1)
        self.pushButton_limpar = QtWidgets.QPushButton(self.frame_botoes)
        self.pushButton_limpar.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton_limpar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_limpar.setFont(font)
        self.pushButton_limpar.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_limpar.setObjectName("pushButton_limpar")
        self.frame_buttonsLayout.addWidget(self.pushButton_limpar)
        self.pushButton_realizar = QtWidgets.QPushButton(self.frame_botoes)
        self.pushButton_realizar.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 255, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 212, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 113, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 212, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 255, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 212, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 113, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 212, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 255, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 212, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 113, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton_realizar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_realizar.setFont(font)
        self.pushButton_realizar.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_realizar.setObjectName("pushButton_realizar")
        self.frame_buttonsLayout.addWidget(self.pushButton_realizar)
        self.gridLayout_2.addWidget(self.frame_botoes, 2, 0, 1, 1)
        self.horizontalLayout_remanufaturas_2 = QtWidgets.QFrame(self.frame)
        self.horizontalLayout_remanufaturas_2.setObjectName("horizontalLayout_remanufaturas_2")
        self.horizontalLayout_remanufaturas = QtWidgets.QHBoxLayout(self.horizontalLayout_remanufaturas_2)
        self.horizontalLayout_remanufaturas.setObjectName("horizontalLayout_remanufaturas")
        self.groupBox_remanufaturas = QtWidgets.QGroupBox(self.horizontalLayout_remanufaturas_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_remanufaturas.setFont(font)
        self.groupBox_remanufaturas.setObjectName("groupBox_remanufaturas")
        self.horizontalLayout_info = QtWidgets.QHBoxLayout(self.groupBox_remanufaturas)
        self.horizontalLayout_info.setSpacing(10)
        self.horizontalLayout_info.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_info.setObjectName("horizontalLayout_info")
        self.frame_itens = QtWidgets.QFrame(self.groupBox_remanufaturas)
        self.frame_itens.setObjectName("frame_itens")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_itens)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_remanufaturas = QtWidgets.QTableWidget(self.frame_itens)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tableWidget_remanufaturas.setFont(font)
        self.tableWidget_remanufaturas.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget_remanufaturas.setLineWidth(1)
        self.tableWidget_remanufaturas.setAutoScrollMargin(17)
        self.tableWidget_remanufaturas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_remanufaturas.setProperty("showDropIndicator", False)
        self.tableWidget_remanufaturas.setDragEnabled(False)
        self.tableWidget_remanufaturas.setAlternatingRowColors(False)
        self.tableWidget_remanufaturas.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget_remanufaturas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_remanufaturas.setShowGrid(True)
        self.tableWidget_remanufaturas.setWordWrap(False)
        self.tableWidget_remanufaturas.setRowCount(0)
        self.tableWidget_remanufaturas.setColumnCount(0)
        self.tableWidget_remanufaturas.setObjectName("tableWidget_remanufaturas")
        self.tableWidget_remanufaturas.setColumnCount(0)
        self.tableWidget_remanufaturas.setRowCount(0)
        self.tableWidget_remanufaturas.horizontalHeader().setVisible(True)
        self.tableWidget_remanufaturas.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_remanufaturas.horizontalHeader().setHighlightSections(False)
        self.tableWidget_remanufaturas.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_remanufaturas.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_remanufaturas.verticalHeader().setVisible(False)
        self.tableWidget_remanufaturas.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.tableWidget_remanufaturas)
        self.checkBox_selecionar_tudo = QtWidgets.QCheckBox(self.frame_itens)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBox_selecionar_tudo.setFont(font)
        self.checkBox_selecionar_tudo.setObjectName("checkBox_selecionar_tudo")
        self.verticalLayout_2.addWidget(self.checkBox_selecionar_tudo)
        self.horizontalLayout_info.addWidget(self.frame_itens)
        self.horizontalLayout_remanufaturas.addWidget(self.groupBox_remanufaturas)
        self.groupBox_insumo = QtWidgets.QGroupBox(self.horizontalLayout_remanufaturas_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_insumo.setFont(font)
        self.groupBox_insumo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_insumo.setObjectName("groupBox_insumo")
        self.verticalLayout_groupBox_insumo = QtWidgets.QVBoxLayout(self.groupBox_insumo)
        self.verticalLayout_groupBox_insumo.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_groupBox_insumo.setObjectName("verticalLayout_groupBox_insumo")
        self.verticalLayout_insumo = QtWidgets.QVBoxLayout()
        self.verticalLayout_insumo.setObjectName("verticalLayout_insumo")
        self.frame_insumo = QtWidgets.QFrame(self.groupBox_insumo)
        self.frame_insumo.setObjectName("frame_insumo")
        self.horizontalLayout_frame_insumo = QtWidgets.QHBoxLayout(self.frame_insumo)
        self.horizontalLayout_frame_insumo.setObjectName("horizontalLayout_frame_insumo")
        self.label_icone_item_lote = QtWidgets.QLabel(self.frame_insumo)
        self.label_icone_item_lote.setText("")
        self.label_icone_item_lote.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icone_item_lote.setObjectName("label_icone_item_lote")
        self.horizontalLayout_frame_insumo.addWidget(self.label_icone_item_lote)
        self.label_item_lote_descricao = QtWidgets.QLabel(self.frame_insumo)
        self.label_item_lote_descricao.setMinimumSize(QtCore.QSize(256, 0))
        self.label_item_lote_descricao.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_item_lote_descricao.setFont(font)
        self.label_item_lote_descricao.setText("")
        self.label_item_lote_descricao.setAlignment(QtCore.Qt.AlignCenter)
        self.label_item_lote_descricao.setWordWrap(True)
        self.label_item_lote_descricao.setObjectName("label_item_lote_descricao")
        self.horizontalLayout_frame_insumo.addWidget(self.label_item_lote_descricao)
        self.verticalLayout_insumo.addWidget(self.frame_insumo)
        self.frame_insumo_item = QtWidgets.QFrame(self.groupBox_insumo)
        self.frame_insumo_item.setMinimumSize(QtCore.QSize(310, 0))
        self.frame_insumo_item.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_insumo_item.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_insumo_item.setLineWidth(0)
        self.frame_insumo_item.setObjectName("frame_insumo_item")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_insumo_item)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_insumo_item)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 432, 233))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formFrame_item_lote = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.formFrame_item_lote.setFont(font)
        self.formFrame_item_lote.setToolTipDuration(10000)
        self.formFrame_item_lote.setFrameShadow(QtWidgets.QFrame.Plain)
        self.formFrame_item_lote.setObjectName("formFrame_item_lote")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame_item_lote)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_item_lote_fabricante = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_item_lote_fabricante.setFont(font)
        self.label_item_lote_fabricante.setText("")
        self.label_item_lote_fabricante.setObjectName("label_item_lote_fabricante")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_fabricante)
        self.label_2 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dateEdit_entrada = QtWidgets.QDateEdit(self.formFrame_item_lote)
        self.dateEdit_entrada.setEnabled(True)
        self.dateEdit_entrada.setMinimumSize(QtCore.QSize(0, 15))
        self.dateEdit_entrada.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.dateEdit_entrada.setFont(font)
        self.dateEdit_entrada.setWrapping(False)
        self.dateEdit_entrada.setFrame(False)
        self.dateEdit_entrada.setReadOnly(True)
        self.dateEdit_entrada.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_entrada.setSpecialValueText("")
        self.dateEdit_entrada.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateEdit_entrada.setKeyboardTracking(False)
        self.dateEdit_entrada.setProperty("showGroupSeparator", False)
        self.dateEdit_entrada.setCalendarPopup(False)
        self.dateEdit_entrada.setDate(QtCore.QDate(2001, 1, 1))
        self.dateEdit_entrada.setObjectName("dateEdit_entrada")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit_entrada)
        self.label_5 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.dateEdit_abertura = QtWidgets.QDateEdit(self.formFrame_item_lote)
        self.dateEdit_abertura.setEnabled(True)
        self.dateEdit_abertura.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.dateEdit_abertura.setFont(font)
        self.dateEdit_abertura.setFrame(False)
        self.dateEdit_abertura.setReadOnly(True)
        self.dateEdit_abertura.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_abertura.setSpecialValueText("")
        self.dateEdit_abertura.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateEdit_abertura.setKeyboardTracking(False)
        self.dateEdit_abertura.setProperty("showGroupSeparator", False)
        self.dateEdit_abertura.setCalendarPopup(False)
        self.dateEdit_abertura.setDate(QtCore.QDate(2001, 1, 1))
        self.dateEdit_abertura.setObjectName("dateEdit_abertura")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dateEdit_abertura)
        self.label_4 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dateEdit_validade = QtWidgets.QDateEdit(self.formFrame_item_lote)
        self.dateEdit_validade.setEnabled(True)
        self.dateEdit_validade.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.dateEdit_validade.setFont(font)
        self.dateEdit_validade.setFrame(False)
        self.dateEdit_validade.setReadOnly(True)
        self.dateEdit_validade.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_validade.setSpecialValueText("")
        self.dateEdit_validade.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateEdit_validade.setKeyboardTracking(False)
        self.dateEdit_validade.setProperty("showGroupSeparator", False)
        self.dateEdit_validade.setCalendarPopup(False)
        self.dateEdit_validade.setCurrentSectionIndex(0)
        self.dateEdit_validade.setDate(QtCore.QDate(2001, 1, 1))
        self.dateEdit_validade.setObjectName("dateEdit_validade")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateEdit_validade)
        self.label_6 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_item_lote_aberto = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_item_lote_aberto.setFont(font)
        self.label_item_lote_aberto.setText("")
        self.label_item_lote_aberto.setObjectName("label_item_lote_aberto")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_aberto)
        self.label_11 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_item_lote_vazio = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_item_lote_vazio.setFont(font)
        self.label_item_lote_vazio.setText("")
        self.label_item_lote_vazio.setObjectName("label_item_lote_vazio")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_vazio)
        self.label_7 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_item_lote_lote_id = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_item_lote_lote_id.setFont(font)
        self.label_item_lote_lote_id.setText("")
        self.label_item_lote_lote_id.setObjectName("label_item_lote_lote_id")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_lote_id)
        self.label = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_item_lote_id = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_item_lote_id.setFont(font)
        self.label_item_lote_id.setText("")
        self.label_item_lote_id.setObjectName("label_item_lote_id")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_id)
        self.label_3 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setToolTipDuration(10000)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_item_lote_quantidade_remanufaturas = QtWidgets.QLabel(self.formFrame_item_lote)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(221, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 16, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_item_lote_quantidade_remanufaturas.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_item_lote_quantidade_remanufaturas.setFont(font)
        self.label_item_lote_quantidade_remanufaturas.setText("")
        self.label_item_lote_quantidade_remanufaturas.setObjectName("label_item_lote_quantidade_remanufaturas")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_quantidade_remanufaturas)
        self.verticalLayout_5.addWidget(self.formFrame_item_lote)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.pushButton_esvaziar = QtWidgets.QPushButton(self.frame_insumo_item)
        self.pushButton_esvaziar.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_esvaziar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_esvaziar.setFont(font)
        self.pushButton_esvaziar.setToolTipDuration(10000)
        self.pushButton_esvaziar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_esvaziar.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_esvaziar.setFlat(True)
        self.pushButton_esvaziar.setObjectName("pushButton_esvaziar")
        self.verticalLayout.addWidget(self.pushButton_esvaziar)
        self.verticalLayout_insumo.addWidget(self.frame_insumo_item)
        self.verticalLayout_groupBox_insumo.addLayout(self.verticalLayout_insumo)
        self.horizontalLayout_remanufaturas.addWidget(self.groupBox_insumo)
        self.gridLayout_2.addWidget(self.horizontalLayout_remanufaturas_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(RegistroRemanufatura)
        QtCore.QMetaObject.connectSlotsByName(RegistroRemanufatura)

    def retranslateUi(self, RegistroRemanufatura):
        RegistroRemanufatura.setWindowTitle(QtWidgets.QApplication.translate("RegistroRemanufatura", "SOAD - Realizar Remanufaturas", None, -1))
        self.groupBox_identificacao.setTitle(QtWidgets.QApplication.translate("RegistroRemanufatura", "Identificação", None, -1))
        self.label_codigo.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Código", None, -1))
        self.lineEdit_codigo.setToolTip(QtWidgets.QApplication.translate("RegistroRemanufatura", "Quando uma remanufatura for realizada, irá gerar um identificador único.", None, -1))
        self.lineEdit_codigo.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "AUTO GERADO", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Medida:", None, -1))
        self.label_medida.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "0,00g", None, -1))
        self.label_casco.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Casco", None, -1))
        self.label_insumo.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Insumo", None, -1))
        self.label_tinta.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "TextLabel", None, -1))
        self.label_situacao.setToolTip(QtWidgets.QApplication.translate("RegistroRemanufatura", "Apenas podem ser realizadas remanufaturas na situação \"Cadastrada\".\n"
"Remanufaturas em outras situações não podem ser alteradas", None, -1))
        self.label_situacao.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "SITUACAO", None, -1))
        self.pushButton_limpar.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Remover remanufaturas", None, -1))
        self.pushButton_realizar.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Realizar remanufaturas", None, -1))
        self.groupBox_remanufaturas.setTitle(QtWidgets.QApplication.translate("RegistroRemanufatura", "Remanufaturas", None, -1))
        self.tableWidget_remanufaturas.setSortingEnabled(True)
        self.checkBox_selecionar_tudo.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Selecionar todos", None, -1))
        self.groupBox_insumo.setTitle(QtWidgets.QApplication.translate("RegistroRemanufatura", "Insumo", None, -1))
        self.formFrame_item_lote.setToolTip(QtWidgets.QApplication.translate("RegistroRemanufatura", "O insumo utilizado para realizar as remanufaturas selecionadas", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Fabricante", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Entrada", None, -1))
        self.dateEdit_entrada.setDisplayFormat(QtWidgets.QApplication.translate("RegistroRemanufatura", "dd/MM/yyyy", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Abertura", None, -1))
        self.dateEdit_abertura.setDisplayFormat(QtWidgets.QApplication.translate("RegistroRemanufatura", "dd/MM/yyyy", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Validade", None, -1))
        self.dateEdit_validade.setDisplayFormat(QtWidgets.QApplication.translate("RegistroRemanufatura", "dd/MM/yyyy", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Aberto", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Vazio", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Lote", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Item", None, -1))
        self.label_3.setToolTip(QtWidgets.QApplication.translate("RegistroRemanufatura", "Número de remanufaturas que foram realizadas com esse insumo.", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Qtd. Remanufaturas", None, -1))
        self.pushButton_esvaziar.setToolTip(QtWidgets.QApplication.translate("RegistroRemanufatura", "O insumo posicionado na interface já estiver vazio, clique aqui para marcar como vazio.", None, -1))
        self.pushButton_esvaziar.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Esvaziar Embalagem", None, -1))

