# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources\UI\RegistroRemanufatura.ui',
# licensing of 'Resources\UI\RegistroRemanufatura.ui' applies.
#
# Created: Wed Oct  9 01:04:19 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RegistroRemanufatura(object):
    def setupUi(self, RegistroRemanufatura):
        RegistroRemanufatura.setObjectName("RegistroRemanufatura")
        RegistroRemanufatura.resize(900, 700)
        RegistroRemanufatura.setMinimumSize(QtCore.QSize(900, 700))
        self.gridLayout = QtWidgets.QGridLayout(RegistroRemanufatura)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(RegistroRemanufatura)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_info = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_info.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_info.setObjectName("horizontalLayout_info")
        self.frame_itens = QtWidgets.QFrame(self.frame_2)
        self.frame_itens.setObjectName("frame_itens")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_itens)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_remanufaturas = QtWidgets.QTableWidget(self.frame_itens)
        self.tableWidget_remanufaturas.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget_remanufaturas.setLineWidth(1)
        self.tableWidget_remanufaturas.setAutoScrollMargin(17)
        self.tableWidget_remanufaturas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_remanufaturas.setProperty("showDropIndicator", False)
        self.tableWidget_remanufaturas.setDragEnabled(False)
        self.tableWidget_remanufaturas.setAlternatingRowColors(False)
        self.tableWidget_remanufaturas.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget_remanufaturas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_remanufaturas.setShowGrid(True)
        self.tableWidget_remanufaturas.setWordWrap(False)
        self.tableWidget_remanufaturas.setRowCount(0)
        self.tableWidget_remanufaturas.setColumnCount(0)
        self.tableWidget_remanufaturas.setObjectName("tableWidget_remanufaturas")
        self.tableWidget_remanufaturas.setColumnCount(0)
        self.tableWidget_remanufaturas.setRowCount(0)
        self.tableWidget_remanufaturas.horizontalHeader().setVisible(False)
        self.tableWidget_remanufaturas.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_remanufaturas.horizontalHeader().setHighlightSections(False)
        self.tableWidget_remanufaturas.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_remanufaturas.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_remanufaturas.verticalHeader().setVisible(False)
        self.tableWidget_remanufaturas.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.tableWidget_remanufaturas)
        self.checkBox_selecionar_tudo = QtWidgets.QCheckBox(self.frame_itens)
        self.checkBox_selecionar_tudo.setObjectName("checkBox_selecionar_tudo")
        self.verticalLayout_2.addWidget(self.checkBox_selecionar_tudo)
        self.horizontalLayout_info.addWidget(self.frame_itens)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(310, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(310, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setContentsMargins(9, 9, 9, 35)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_icone_item_lote = QtWidgets.QLabel(self.frame_3)
        self.label_icone_item_lote.setText("")
        self.label_icone_item_lote.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icone_item_lote.setObjectName("label_icone_item_lote")
        self.verticalLayout.addWidget(self.label_icone_item_lote)
        self.label_item_lote_descricao = QtWidgets.QLabel(self.frame_3)
        self.label_item_lote_descricao.setMinimumSize(QtCore.QSize(256, 0))
        self.label_item_lote_descricao.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_item_lote_descricao.setFont(font)
        self.label_item_lote_descricao.setAlignment(QtCore.Qt.AlignCenter)
        self.label_item_lote_descricao.setWordWrap(True)
        self.label_item_lote_descricao.setObjectName("label_item_lote_descricao")
        self.verticalLayout.addWidget(self.label_item_lote_descricao)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.formFrame_item_lote = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.formFrame_item_lote.setFont(font)
        self.formFrame_item_lote.setObjectName("formFrame_item_lote")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame_item_lote)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_item_lote_fabricante = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_item_lote_fabricante.setFont(font)
        self.label_item_lote_fabricante.setText("")
        self.label_item_lote_fabricante.setObjectName("label_item_lote_fabricante")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_fabricante)
        self.label_2 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_5 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_4 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_item_lote_aberto = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_item_lote_aberto.setFont(font)
        self.label_item_lote_aberto.setText("")
        self.label_item_lote_aberto.setObjectName("label_item_lote_aberto")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_aberto)
        self.label_11 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_item_lote_vazio = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_item_lote_vazio.setFont(font)
        self.label_item_lote_vazio.setText("")
        self.label_item_lote_vazio.setObjectName("label_item_lote_vazio")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_vazio)
        self.label_7 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_item_lote_lote_id = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_item_lote_lote_id.setFont(font)
        self.label_item_lote_lote_id.setText("")
        self.label_item_lote_lote_id.setObjectName("label_item_lote_lote_id")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_lote_id)
        self.label_item_lote_id = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_item_lote_id.setFont(font)
        self.label_item_lote_id.setText("")
        self.label_item_lote_id.setObjectName("label_item_lote_id")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_id)
        self.label_3 = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label = QtWidgets.QLabel(self.formFrame_item_lote)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_item_lote_quantidade_remanufaturas = QtWidgets.QLabel(self.formFrame_item_lote)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(221, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 16, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_item_lote_quantidade_remanufaturas.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_item_lote_quantidade_remanufaturas.setFont(font)
        self.label_item_lote_quantidade_remanufaturas.setText("")
        self.label_item_lote_quantidade_remanufaturas.setObjectName("label_item_lote_quantidade_remanufaturas")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_item_lote_quantidade_remanufaturas)
        self.dateEdit_entrada = QtWidgets.QDateEdit(self.formFrame_item_lote)
        self.dateEdit_entrada.setEnabled(True)
        self.dateEdit_entrada.setBaseSize(QtCore.QSize(0, 0))
        self.dateEdit_entrada.setWrapping(False)
        self.dateEdit_entrada.setFrame(False)
        self.dateEdit_entrada.setReadOnly(True)
        self.dateEdit_entrada.setSpecialValueText("")
        self.dateEdit_entrada.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateEdit_entrada.setKeyboardTracking(False)
        self.dateEdit_entrada.setProperty("showGroupSeparator", True)
        self.dateEdit_entrada.setCalendarPopup(True)
        self.dateEdit_entrada.setObjectName("dateEdit_entrada")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_entrada)
        self.dateEdit_abertura = QtWidgets.QDateEdit(self.formFrame_item_lote)
        self.dateEdit_abertura.setEnabled(True)
        self.dateEdit_abertura.setFrame(False)
        self.dateEdit_abertura.setReadOnly(True)
        self.dateEdit_abertura.setSpecialValueText("")
        self.dateEdit_abertura.setCalendarPopup(True)
        self.dateEdit_abertura.setObjectName("dateEdit_abertura")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit_abertura)
        self.dateEdit_validade = QtWidgets.QDateEdit(self.formFrame_item_lote)
        self.dateEdit_validade.setEnabled(True)
        self.dateEdit_validade.setFrame(False)
        self.dateEdit_validade.setReadOnly(True)
        self.dateEdit_validade.setSpecialValueText("")
        self.dateEdit_validade.setKeyboardTracking(True)
        self.dateEdit_validade.setCalendarPopup(True)
        self.dateEdit_validade.setCurrentSectionIndex(0)
        self.dateEdit_validade.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEdit_validade.setObjectName("dateEdit_validade")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit_validade)
        self.verticalLayout.addWidget(self.formFrame_item_lote)
        self.pushButton_esvaziar = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_esvaziar.setFont(font)
        self.pushButton_esvaziar.setObjectName("pushButton_esvaziar")
        self.verticalLayout.addWidget(self.pushButton_esvaziar)
        self.horizontalLayout_info.addWidget(self.frame_3)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_acoes = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_acoes.setSpacing(10)
        self.horizontalLayout_acoes.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_acoes.setObjectName("horizontalLayout_acoes")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_acoes.addItem(spacerItem2)
        self.pushButton_limpar = QtWidgets.QPushButton(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(98, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton_limpar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_limpar.setFont(font)
        self.pushButton_limpar.setObjectName("pushButton_limpar")
        self.horizontalLayout_acoes.addWidget(self.pushButton_limpar)
        self.pushButton_realizar = QtWidgets.QPushButton(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 255, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 212, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 113, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 212, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 255, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 212, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 113, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 212, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 255, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 212, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 113, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 85, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 170, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton_realizar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_realizar.setFont(font)
        self.pushButton_realizar.setObjectName("pushButton_realizar")
        self.horizontalLayout_acoes.addWidget(self.pushButton_realizar)
        self.gridLayout_2.addWidget(self.frame_4, 2, 0, 1, 1)
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.frame)
        self.horizontalGroupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.horizontalGroupBox.setFont(font)
        self.horizontalGroupBox.setFlat(False)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setContentsMargins(9, -1, 9, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameFormLayout_remanufatura = QtWidgets.QFrame(self.horizontalGroupBox)
        self.frameFormLayout_remanufatura.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.frameFormLayout_remanufatura.setFont(font)
        self.frameFormLayout_remanufatura.setObjectName("frameFormLayout_remanufatura")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frameFormLayout_remanufatura)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_5.setHorizontalSpacing(9)
        self.formLayout_5.setVerticalSpacing(10)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_codigo = QtWidgets.QLabel(self.frameFormLayout_remanufatura)
        self.label_codigo.setObjectName("label_codigo")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_codigo)
        self.horizontalFrame_4 = QtWidgets.QFrame(self.frameFormLayout_remanufatura)
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalFrame_4)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit.setMaxLength(15)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.spinBox_quantidade = QtWidgets.QSpinBox(self.horizontalFrame_4)
        self.spinBox_quantidade.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_quantidade.setWrapping(False)
        self.spinBox_quantidade.setFrame(True)
        self.spinBox_quantidade.setReadOnly(False)
        self.spinBox_quantidade.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_quantidade.setSpecialValueText("")
        self.spinBox_quantidade.setProperty("showGroupSeparator", False)
        self.spinBox_quantidade.setMinimum(1)
        self.spinBox_quantidade.setObjectName("spinBox_quantidade")
        self.horizontalLayout_2.addWidget(self.spinBox_quantidade)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalFrame_4)
        self.label_casco = QtWidgets.QLabel(self.frameFormLayout_remanufatura)
        self.label_casco.setObjectName("label_casco")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_casco)
        self.horizontalLayout_casco = QtWidgets.QHBoxLayout()
        self.horizontalLayout_casco.setSpacing(10)
        self.horizontalLayout_casco.setObjectName("horizontalLayout_casco")
        self.lineEdit_casco_id = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_casco_id.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_casco_id.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_casco_id.setInputMask("")
        self.lineEdit_casco_id.setObjectName("lineEdit_casco_id")
        self.horizontalLayout_casco.addWidget(self.lineEdit_casco_id)
        self.lineEdit_casco = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_casco.setEnabled(False)
        self.lineEdit_casco.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_casco.setObjectName("lineEdit_casco")
        self.horizontalLayout_casco.addWidget(self.lineEdit_casco)
        self.lineEdit_marca_casco = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_marca_casco.setEnabled(False)
        self.lineEdit_marca_casco.setObjectName("lineEdit_marca_casco")
        self.horizontalLayout_casco.addWidget(self.lineEdit_marca_casco)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_casco)
        self.label_insumo = QtWidgets.QLabel(self.frameFormLayout_remanufatura)
        self.label_insumo.setObjectName("label_insumo")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_insumo)
        self.horizontalLayout_insumo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_insumo.setSpacing(10)
        self.horizontalLayout_insumo.setObjectName("horizontalLayout_insumo")
        self.lineEdit_insumo_id = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_insumo_id.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_insumo_id.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_insumo_id.setInputMask("")
        self.lineEdit_insumo_id.setObjectName("lineEdit_insumo_id")
        self.horizontalLayout_insumo.addWidget(self.lineEdit_insumo_id)
        self.lineEdit_insumo = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_insumo.setEnabled(False)
        self.lineEdit_insumo.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_insumo.setObjectName("lineEdit_insumo")
        self.horizontalLayout_insumo.addWidget(self.lineEdit_insumo)
        self.lineEdit_marca_insumo = QtWidgets.QLineEdit(self.frameFormLayout_remanufatura)
        self.lineEdit_marca_insumo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_marca_insumo.sizePolicy().hasHeightForWidth())
        self.lineEdit_marca_insumo.setSizePolicy(sizePolicy)
        self.lineEdit_marca_insumo.setObjectName("lineEdit_marca_insumo")
        self.horizontalLayout_insumo.addWidget(self.lineEdit_marca_insumo)
        self.formLayout_5.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_insumo)
        self.horizontalLayout.addWidget(self.frameFormLayout_remanufatura)
        self.buttonBox_remanufatura = QtWidgets.QDialogButtonBox(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.buttonBox_remanufatura.setFont(font)
        self.buttonBox_remanufatura.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox_remanufatura.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_remanufatura.setCenterButtons(True)
        self.buttonBox_remanufatura.setObjectName("buttonBox_remanufatura")
        self.horizontalLayout.addWidget(self.buttonBox_remanufatura)
        self.label_tinta = QtWidgets.QLabel(self.horizontalGroupBox)
        self.label_tinta.setMinimumSize(QtCore.QSize(190, 0))
        self.label_tinta.setSizeIncrement(QtCore.QSize(256, 0))
        self.label_tinta.setBaseSize(QtCore.QSize(0, 0))
        self.label_tinta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tinta.setObjectName("label_tinta")
        self.horizontalLayout.addWidget(self.label_tinta)
        self.gridLayout_2.addWidget(self.horizontalGroupBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(RegistroRemanufatura)
        QtCore.QMetaObject.connectSlotsByName(RegistroRemanufatura)

    def retranslateUi(self, RegistroRemanufatura):
        RegistroRemanufatura.setWindowTitle(QtWidgets.QApplication.translate("RegistroRemanufatura", "SOAD - Realizar Remanufaturas", None, -1))
        self.tableWidget_remanufaturas.setSortingEnabled(True)
        self.checkBox_selecionar_tudo.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Selecionar todos", None, -1))
        self.label_item_lote_descricao.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Insumo", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Fabricante", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Entrada", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Abertura", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Validade", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Aberto", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Vazio", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Lote", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Qtd. Remanufaturas", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Item", None, -1))
        self.pushButton_esvaziar.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Esvaziar Embalagem", None, -1))
        self.pushButton_limpar.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Remover remanufaturas", None, -1))
        self.pushButton_realizar.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Realizar remanufaturas", None, -1))
        self.horizontalGroupBox.setTitle(QtWidgets.QApplication.translate("RegistroRemanufatura", "Remanufatura", None, -1))
        self.label_codigo.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Código", None, -1))
        self.lineEdit.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "AUTO GERADO", None, -1))
        self.label_casco.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Casco", None, -1))
        self.label_insumo.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "Insumo", None, -1))
        self.label_tinta.setText(QtWidgets.QApplication.translate("RegistroRemanufatura", "TextLabel", None, -1))

